// Package report renders scan results as a printable HTML page.
//
// The output is a self-contained document (inline CSS, no external
// assets) so it can be saved, emailed, or piped straight to chromedp
// for PDF rendering. Style is intentionally minimal — think "Stripe
// invoice", not "marketing site".
package report

import (
	"fmt"
	"html"
	"net/url"
	"strings"
	"time"

	"github.com/dikdotcom/stackly/internal/scanner"
)

// Data wraps the result with metadata needed for the report header.
type Data struct {
	Result    *scanner.ScanResult
	JobID     string
	Generated time.Time
	ServerURL string // for "Powered by" footer
}

// Render returns a self-contained HTML page representing the scan.
func Render(d Data) string {
	if d.Generated.IsZero() {
		d.Generated = time.Now()
	}
	r := d.Result
	if r == nil {
		return minimalErrorPage("no result", d.Generated)
	}

	var b strings.Builder
	b.WriteString(`<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">`)
	fmt.Fprintf(&b, `<title>Stackly Report — %s</title>`, html.EscapeString(r.URL))
	b.WriteString(`<style>` + reportCSS + `</style></head><body>`)

	// Header
	b.WriteString(`<header class="hdr">`)
	fmt.Fprintf(&b, `<div class="hdr-row"><div class="hdr-brand">Stackly</div><div class="hdr-meta">%s</div></div>`,
		d.Generated.UTC().Format("2006-01-02 15:04 UTC"))
	fmt.Fprintf(&b, `<h1 class="hdr-url">%s</h1>`, html.EscapeString(r.URL))
	b.WriteString(`<div class="hdr-stats">`)
	fmt.Fprintf(&b, `<div class="hdr-stat"><div class="hdr-stat-label">Scan ID</div><div class="hdr-stat-val mono">%s</div></div>`, html.EscapeString(d.JobID))
	if r.ScanDuration > 0 {
		fmt.Fprintf(&b, `<div class="hdr-stat"><div class="hdr-stat-label">Duration</div><div class="hdr-stat-val">%s</div></div>`, r.ScanDuration.Round(time.Millisecond))
	}
	if len(r.Results) > 0 {
		fmt.Fprintf(&b, `<div class="hdr-stat"><div class="hdr-stat-label">Technologies</div><div class="hdr-stat-val">%d</div></div>`, len(r.Results))
	}
	b.WriteString(`</div></header>`)

	// Tech stack
	b.WriteString(renderSection("Tech Stack", "technologies",
		renderTechPills(r.Results)))

	// Enrichment: 2-column grid
	b.WriteString(`<section class="sec"><h2>Enrichment</h2><div class="grid-2">`)
	b.WriteString(renderDNS(r.DNS))
	b.WriteString(renderWHOIS(r.WHOIS))
	b.WriteString(renderSSL(r.SSL))
	b.WriteString(renderPerf(r.Perf))
	b.WriteString(`</div></section>`)

	// Emails (if any)
	if len(r.Emails) > 0 {
		b.WriteString(renderSection("Contact Emails", "emails",
			renderEmails(r.Emails)))
	}

	// Footer
	if d.ServerURL != "" {
		fmt.Fprintf(&b, `<footer class="ftr">Generated by <a href="%s">%s</a></footer>`,
			html.EscapeString(d.ServerURL), html.EscapeString(d.ServerURL))
	} else {
		b.WriteString(`<footer class="ftr">Generated by Stackly</footer>`)
	}

	b.WriteString(`</body></html>`)
	return b.String()
}

// ─── section helpers ────────────────────────────────────────────

func renderSection(title, id, body string) string {
	return fmt.Sprintf(`<section class="sec" id="%s"><h2>%s</h2>%s</section>`,
		html.EscapeString(id), html.EscapeString(title), body)
}

func renderTechPills(techs []scanner.Result) string {
	if len(techs) == 0 {
		return `<div class="empty">No technologies detected.</div>`
	}
	// Group by category
	byCat := make(map[string][]scanner.Result)
	order := make([]string, 0)
	catNames := map[string]string{
		"webserver": "Web Servers", "cdn": "CDN", "cms": "CMS",
		"framework": "Frameworks", "analytics": "Analytics",
		"database": "Databases", "language": "Languages",
		"security": "Security", "ssl": "SSL/TLS",
		"hosting": "Hosting", "marketing": "Marketing",
		"javascript": "JavaScript Libraries",
	}
	for _, t := range techs {
		cat := t.Technology.Category
		if _, ok := byCat[cat]; !ok {
			order = append(order, cat)
		}
		byCat[cat] = append(byCat[cat], t)
	}

	var b strings.Builder
	for _, cat := range order {
		display := catNames[cat]
		if display == "" {
			display = strings.Title(cat)
		}
		fmt.Fprintf(&b, `<div class="cat-block"><h3 class="cat-title">%s</h3><div class="pills">`,
			html.EscapeString(display))
		for _, t := range byCat[cat] {
			conf := ""
			if t.Confidence > 0 && t.Confidence < 100 {
				conf = fmt.Sprintf(` <span class="pill-conf">%d%%</span>`, t.Confidence)
			}
			if t.Technology.Website != "" {
				href := t.Technology.Website
				fmt.Fprintf(&b, `<a class="pill pill-link" href="%s" target="_blank" rel="noopener">%s%s</a>`,
					html.EscapeString(href), html.EscapeString(t.Technology.Name), conf)
			} else {
				fmt.Fprintf(&b, `<span class="pill">%s%s</span>`,
					html.EscapeString(t.Technology.Name), conf)
			}
		}
		b.WriteString(`</div></div>`)
	}
	return b.String()
}

func renderDNS(d *scanner.DNSInfo) string {
	if d == nil {
		return emptyCard("DNS")
	}
	var b strings.Builder
	b.WriteString(`<div class="card"><div class="card-title">DNS</div>`)
	if d.DNSProvider != "" {
		fmt.Fprintf(&b, `<div class="kv"><span class="k">Provider</span><span class="v">%s</span></div>`,
			html.EscapeString(d.DNSProvider))
	}
	writeKVList(&b, "A Records", d.A)
	writeKVList(&b, "AAAA Records", d.AAAA)
	writeKVList(&b, "NS Records", d.NS)
	writeKVList(&b, "TXT Records", d.TXT)
	if len(d.MX) > 0 {
		mxs := make([]string, 0, len(d.MX))
		for _, m := range d.MX {
			if m.Host != "" {
				mxs = append(mxs, fmt.Sprintf("%s (pref %d)", m.Host, m.Pref))
			}
		}
		writeKVList(&b, "MX Records", mxs)
	}
	if d.EmailProvider != "" {
		fmt.Fprintf(&b, `<div class="kv"><span class="k">Email Provider</span><span class="v">%s</span></div>`,
			html.EscapeString(d.EmailProvider))
	}
	if d.Error != "" {
		fmt.Fprintf(&b, `<div class="kv"><span class="k">Error</span><span class="v err">%s</span></div>`,
			html.EscapeString(d.Error))
	}
	b.WriteString(`</div>`)
	return b.String()
}

func renderWHOIS(w *scanner.WHOISInfo) string {
	if w == nil {
		return emptyCard("WHOIS")
	}
	var b strings.Builder
	b.WriteString(`<div class="card"><div class="card-title">WHOIS</div>`)
	writeKV(&b, "Registrar", w.Registrar)
	writeKV(&b, "Created", w.CreatedDate)
	writeKV(&b, "Expires", w.ExpiryDate)
	writeKV(&b, "Updated", w.UpdatedDate)
	if w.DomainAgeDays > 0 {
		fmt.Fprintf(&b, `<div class="kv"><span class="k">Age</span><span class="v">%d days</span></div>`, w.DomainAgeDays)
	}
	if w.DaysToExpiry > 0 {
		fmt.Fprintf(&b, `<div class="kv"><span class="k">Expires in</span><span class="v">%d days</span></div>`, w.DaysToExpiry)
	}
	if len(w.Status) > 0 {
		writeKVList(&b, "Status", w.Status)
	}
	if len(w.NameServers) > 0 {
		writeKVList(&b, "Name Servers", w.NameServers)
	}
	if w.Error != "" {
		fmt.Fprintf(&b, `<div class="kv"><span class="k">Error</span><span class="v err">%s</span></div>`,
			html.EscapeString(w.Error))
	}
	b.WriteString(`</div>`)
	return b.String()
}

func renderSSL(s *scanner.SSLInfo) string {
	if s == nil {
		return emptyCard("SSL / TLS")
	}
	var b strings.Builder
	b.WriteString(`<div class="card"><div class="card-title">SSL / TLS</div>`)
	writeKV(&b, "Issuer", s.Issuer)
	writeKV(&b, "Subject", s.Subject)
	writeKV(&b, "TLS Version", s.TLSVersion)
	writeKV(&b, "Cipher", s.CipherSuite)
	if s.SANCount > 0 {
		fmt.Fprintf(&b, `<div class="kv"><span class="k">SAN Count</span><span class="v">%d</span></div>`, s.SANCount)
	}
	if s.SelfSigned {
		b.WriteString(`<div class="kv"><span class="k">Self-Signed</span><span class="v warn">Yes</span></div>`)
	}
	if !s.NotAfter.IsZero() {
		days := int(s.NotAfter.Sub(time.Now()).Hours() / 24)
		cls := "v"
		if days < 0 {
			cls = "v err"
		} else if days < 30 {
			cls = "v warn"
		}
		fmt.Fprintf(&b, `<div class="kv"><span class="k">Expires</span><span class="%s">%s (%d days)</span></div>`,
			cls, s.NotAfter.Format("2006-01-02"), days)
	}
	if s.Error != "" {
		fmt.Fprintf(&b, `<div class="kv"><span class="k">Error</span><span class="v err">%s</span></div>`,
			html.EscapeString(s.Error))
	}
	b.WriteString(`</div>`)
	return b.String()
}

func renderPerf(p *scanner.PerfMetrics) string {
	if p == nil {
		return emptyCard("Performance")
	}
	var b strings.Builder
	b.WriteString(`<div class="card"><div class="card-title">Performance</div>`)
	if p.TTFB > 0 {
		fmt.Fprintf(&b, `<div class="kv"><span class="k">TTFB</span><span class="v">%d ms</span></div>`, p.TTFB)
	}
	if p.TotalDuration > 0 {
		fmt.Fprintf(&b, `<div class="kv"><span class="k">Total</span><span class="v">%d ms</span></div>`, p.TotalDuration)
	}
	fmt.Fprintf(&b, `<div class="kv"><span class="k">HTML Size</span><span class="v">%s</span></div>`, humanBytes(p.HTMLSizeBytes))
	fmt.Fprintf(&b, `<div class="kv"><span class="k">JS Bundle</span><span class="v">%s</span></div>`, humanBytes(p.JSBundleSizeBytes))
	fmt.Fprintf(&b, `<div class="kv"><span class="k">CSS Bundle</span><span class="v">%s</span></div>`, humanBytes(p.CSSBundleSizeBytes))
	fmt.Fprintf(&b, `<div class="kv"><span class="k">Scripts</span><span class="v">%d</span></div>`, p.ScriptCount)
	fmt.Fprintf(&b, `<div class="kv"><span class="k">Stylesheets</span><span class="v">%d</span></div>`, p.StylesheetCount)
	fmt.Fprintf(&b, `<div class="kv"><span class="k">Images</span><span class="v">%d</span></div>`, p.ImagesCount)
	fmt.Fprintf(&b, `<div class="kv"><span class="k">Links</span><span class="v">%d</span></div>`, p.LinksCount)
	fmt.Fprintf(&b, `<div class="kv"><span class="k">Headings</span><span class="v">%d</span></div>`, p.HeadingsCount)
	b.WriteString(`</div>`)
	return b.String()
}

func renderEmails(emails []string) string {
	var b strings.Builder
	b.WriteString(`<div class="emails">`)
	for _, e := range emails {
		fmt.Fprintf(&b, `<a class="email-pill" href="mailto:%s">%s</a>`,
			html.EscapeString(e), html.EscapeString(e))
	}
	b.WriteString(`</div>`)
	return b.String()
}

// ─── small helpers ──────────────────────────────────────────────

func writeKV(b *strings.Builder, k, v string) {
	if v == "" {
		return
	}
	fmt.Fprintf(b, `<div class="kv"><span class="k">%s</span><span class="v">%s</span></div>`,
		html.EscapeString(k), html.EscapeString(v))
}

func writeKVList(b *strings.Builder, k string, vals []string) {
	if len(vals) == 0 {
		return
	}
	b.WriteString(`<div class="kv"><span class="k">`)
	html.EscapeString(k)
	b.WriteString(`</span><span class="v">`)
	for i, v := range vals {
		if i > 0 {
			b.WriteString(`<br>`)
		}
		fmt.Fprintf(b, `%s`, html.EscapeString(v))
	}
	b.WriteString(`</span></div>`)
}

func emptyCard(name string) string {
	return fmt.Sprintf(`<div class="card"><div class="card-title">%s</div><div class="empty">Not available</div></div>`,
		html.EscapeString(name))
}

func minimalErrorPage(msg string, ts time.Time) string {
	return fmt.Sprintf(`<!DOCTYPE html><html><body><h1>Report unavailable</h1><p>%s</p><p>%s</p></body></html>`,
		html.EscapeString(msg), ts.Format(time.RFC3339))
}

func humanBytes(n int64) string {
	const k = 1024
	if n < k {
		return fmt.Sprintf("%d B", n)
	}
	if n < k*k {
		return fmt.Sprintf("%.1f KB", float64(n)/k)
	}
	return fmt.Sprintf("%.2f MB", float64(n)/(k*k))
}

// EscapeURL is a convenience for callers that need to encode URLs into
// href attributes without importing net/url.
func EscapeURL(s string) string {
	return url.QueryEscape(s)
}
